name: Bug Report
description: Report a bug or issue with AssertLang
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run command...
        2. See error...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - PW Parser
        - Code Generator (Python)
        - Code Generator (Go)
        - Code Generator (Rust)
        - Code Generator (TypeScript)
        - Code Generator (C#)
        - CLI Tool
        - SDK (Python)
        - SDK (JavaScript)
        - SDK (Go)
        - SDK (.NET)
        - Type System
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: AssertLang Version
      description: What version are you using?
      placeholder: "v2.1.0-beta"
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample (if applicable)
      description: Minimal code sample to reproduce the issue
      render: pw
      placeholder: |
        function example() {
            // Your PW code here
        }

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Paste any error messages or stack traces
      render: shell
      placeholder: Paste error output here

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
