name: Bug Report
description: Report a bug or unexpected behavior in Promptware
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the information below to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Use .pw file with '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected outcome
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually occurred
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Output of `python --version`
      placeholder: e.g., Python 3.11.5
    validations:
      required: true

  - type: input
    id: promptware-version
    attributes:
      label: Promptware Version
      description: Output of `promptware --version` or commit hash if using from source
      placeholder: e.g., 0.1.0 or commit abc123
    validations:
      required: true

  - type: dropdown
    id: language-generated
    attributes:
      label: Target Language (if relevant)
      description: Which language were you generating code for?
      options:
        - Python
        - Node.js
        - Go
        - Rust
        - .NET
        - C++
        - Not applicable
    validations:
      required: false

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: Minimal .pw file or code snippet that reproduces the issue
      placeholder: |
        ```promptware
        server calculator "A simple calculator"
        tool add(a: number, b: number) -> number
        ```
      render: text
    validations:
      required: false

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages / Logs
      description: Full error messages, stack traces, or relevant log output
      placeholder: Paste error messages here
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I am using the latest version of Promptware
          required: true
        - label: I have included all relevant information above
          required: true
