blank_issues_enabled: true
contact_links:
  - name: 💬 Discussions
    url: https://github.com/Promptware-dev/promptware/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/Promptware-dev/promptware/tree/main/docs
    about: Read the documentation for guides and references
  - name: 🚀 Quick Start
    url: https://github.com/Promptware-dev/promptware#readme
    about: Get started with Promptware quickly
