name: Build & Verify

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build twine check-wheel-contents

    - name: Build package
      run: |
        python -m build

    - name: Check distribution files
      run: |
        ls -lh dist/
        twine check dist/*

    - name: Verify wheel contents
      run: |
        check-wheel-contents dist/*.whl

    - name: Test installation from wheel
      run: |
        pip install dist/*.whl
        asl --version
        python -c "import assertlang; print(assertlang.__version__)"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v5
      with:
        name: dist-packages
        path: dist/
        retention-days: 7

  test-install:
    name: Test Install on ${{ matrix.os }}
    needs: build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-packages
        path: dist/

    - name: Install from wheel
      run: |
        pip install dist/*.whl

    - name: Verify installation
      run: |
        asl --version
        asl --help
        python -c "import assertlang; print('✅ AssertLang imported successfully')"
