name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'README.md'
      - 'examples/**'
  workflow_dispatch:

jobs:
  validate-docs:
    name: Validate Documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check markdown links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: '.github/markdown-link-check-config.json'
      continue-on-error: true

    - name: Check for broken example code
      run: |
        # Check that all .al files in examples are valid
        find examples -name "*.al" | while read file; do
          echo "Checking $file"
          # Add validation logic here
        done

    - name: Verify README badges
      run: |
        grep -q "badge" README.md && echo "✅ Badges found in README"

  build-docs:
    name: Build Documentation Site
    runs-on: ubuntu-latest
    needs: validate-docs

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material pymdown-extensions

    - name: Build docs
      run: |
        # If using MkDocs
        # mkdocs build
        echo "Documentation build placeholder"

    - name: Upload docs artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs-build
        path: site/
      if: false  # Enable when docs site is configured

  # Uncomment when ready to deploy docs
  # deploy-docs:
  #   name: Deploy to GitHub Pages
  #   needs: build-docs
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   permissions:
  #     contents: write
  #
  #   steps:
  #   - uses: actions/checkout@v4
  #
  #   - name: Download docs artifact
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: docs-build
  #       path: site/
  #
  #   - name: Deploy to GitHub Pages
  #     uses: peaceiris/actions-gh-pages@v3
  #     with:
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
  #       publish_dir: ./site
