name: Simple CI

# Only run on main branch and PRs to main - no spam on every push
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Run basic tests
      run: |
        python -m pytest tests/ --tb=short || true

    - name: Test CLI
      run: |
        python -m promptware.cli --version || echo "CLI check skipped"
